"use client";

import { BadgeCheck } from "lucide-react";

export default function DigitalCertificate() {
  return (
    <div className="h-full border-r border-dashed border-gray-300 px-5">
      {/* Heading */}
      <h3 className="inline-block border-b-2 border-orange-500 pb-1 text-[13px] font-bold uppercase tracking-[0.12em] text-slate-900">
        Digital Certificate
      </h3>

      {/* Description */}
      <p className="mt-3 text-[12px] leading-5 text-slate-700">
        This certificate has been digitally generated by{" "}
        <span className="font-semibold text-slate-900">Sultan Tracker</span> and
        does not require any handwritten signature or company seal.
      </p>

      {/* Powered By Card */}
      <div className="mt-1 rounded-lg border border-orange-200 bg-orange-50 px-4 py-3 text-center">
        <div className="flex items-center justify-center gap-2 text-orange-600">
          <BadgeCheck size={15} />

          <span className="text-[12px] font-bold">
            Powered by Forbit Limited
          </span>
        </div>

        <p className="mt-1 text-[11px] text-slate-600">
          Smart Vehicle Tracking Solution
        </p>
      </div>
    </div>
  );
}
