"use client";

import { Building2, Globe, Mail, Phone, MapPin } from "lucide-react";

export default function Footer() {
  return (
    <footer className="mt-8 border-t-2 border-gray-300 pt-6">
      <div className="grid grid-cols-2 gap-10">
        <div>
          <h3 className="mb-4 text-sm font-bold uppercase tracking-widest text-gray-900">
            Contact Information
          </h3>

          <div className="space-y-3 text-sm text-gray-700">
            <Item icon={<Building2 size={16} />} value="Forbit Limited" />

            <Item
              icon={<MapPin size={16} />}
              value="24/25 Dilkusha C/A (3rd Floor), Motijheel, Dhaka-1000"
            />

            <Item icon={<Phone size={16} />} value="01409962099" />

            <Item icon={<Globe size={16} />} value="www.sultantracker.com" />

            <Item icon={<Mail size={16} />} value="support@sultantracker.com" />
          </div>
        </div>

        <div className="flex flex-col justify-between text-right">
          <div>
            <h3 className="text-sm font-bold uppercase tracking-widest text-gray-900">
              Digital Certificate
            </h3>

            <p className="mt-3 text-sm leading-7 text-gray-600">
              This certificate has been digitally generated by
              <span className="font-semibold"> Sultan Tracker</span> and does
              not require any handwritten signature or company seal.
            </p>
          </div>

          <div className="rounded-lg border border-orange-200 bg-orange-50 px-5 py-4">
            <p className="text-lg font-bold text-orange-600">
              Powered by Forbit Limited
            </p>

            <p className="mt-1 text-sm text-gray-600">
              Smart Vehicle Tracking Solution
            </p>
          </div>
        </div>
      </div>

      <div className="mt-6 border-t pt-4 text-center">
        <p className="text-xs tracking-wide text-gray-500">
          © {new Date().getFullYear()} Sultan Tracker • Powered by Forbit
          Limited • All Rights Reserved
        </p>
      </div>
    </footer>
  );
}

function Item({ icon, value }: { icon: React.ReactNode; value: string }) {
  return (
    <div className="flex items-start gap-3">
      <div className="mt-0.5 text-orange-500">{icon}</div>

      <span>{value}</span>
    </div>
  );
}
