"use client";

export default function SignatureBox() {
  return (
    <div className="flex h-full flex-col justify-between pl-6">
      <div>
        <h3 className="text-lg font-bold uppercase tracking-wider text-slate-900">
          Digital Certificate
        </h3>

        <p className="mt-4 text-[13px] leading-7 text-slate-700">
          This certificate has been digitally generated by
          <strong> Sultan Tracker </strong>
          and therefore does not require any handwritten signature or company
          seal.
        </p>
      </div>

      <div className="mt-8 rounded-xl border border-orange-200 bg-orange-50 p-5">
        <p className="text-center text-2xl font-semibold italic text-slate-800">
          Sultan Tracker
        </p>

        <div className="mx-auto mt-3 h-px w-48 bg-gray-400" />

        <p className="mt-3 text-center text-sm font-semibold text-slate-700">
          Authorized Digital Signature
        </p>

        <p className="mt-1 text-center text-xs text-gray-500">
          Powered by Forbit Limited
        </p>
      </div>
    </div>
  );
}
